version: '3'
services:
  electrumx:
    image: lucky2077/atomicals-electrumx:latest
    restart: always
    ports:
      - 50001:50001
      - 50002:50002
      - 50004:50004
      - 8000:8000
    volumes:
      - /Volumes/WD_Steve/Shares/atomicals-electrumx-data:/data
    environment:
      - DAEMON_URL=${DAEMON_URL:?}
      - COIN=BitCoin
      
